language: cpp

jobs:
  include:
    - name: Ubuntu 18.04
      os: linux
      dist: bionic

before_install:
  - sudo apt-get update;
    sudo apt-get -y install git wget unzip build-essential software-properties-common cmake rsync libboost-all-dev;

script:
  - ./setup.sh;
    ./build.sh || travis_terminate 1;
    echo "Starting Unity Build!";
    cd Unity && ./build.sh 2> Unity_error.txt || ((cat Unity_error.txt | grep -i "error:" -B 10 -A 10) && exit 1);
